# Generated by Django 4.1.2 on 2022-11-29 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
                ('food_suggestions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=30)),
                ('healthy_serum_k_ul', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_k_ll', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_phos_ul', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_phos_ll', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_na_ul', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_na_ll', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_creatinine_ul_men', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_creatinine_ll_men', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_creatinine_ul_women', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_creatinine_ll_women', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_albumin_ul', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_albumin_ll', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_bloodsugar_ul', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_serum_bloodsugar_ll', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_sodium_ul', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_sodium_ll', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_protein_ul', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_protein_ll', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_water_ul_men', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_water_ll_men', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_water_ul_women', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_water_ll_women', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_k_ul', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_k_ll', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_phos_ul', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthy_dv_phos_ll', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height_feet', models.IntegerField(default=0)),
                ('height_inches', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('morbidity_type', models.ManyToManyField(blank=True, to='trackme.morbidity')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackme.stage')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Na', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creatinine', models.DecimalField(decimal_places=2, max_digits=8)),
                ('albumin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bloodSugar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackme.person')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.today)),
                ('meal', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=50)),
                ('servings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DV_sodium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DV_protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DV_water', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DV_k', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DV_phos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trackme.person')),
            ],
        ),
    ]
